title: Emscripten dynamic linking and pthread
description: This demo shows how to build a dynamic library with pthread support in Emscripten.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman